eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
spring:
    application:
        name: user
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: springstudent
        password: springstudent
        url: jdbc:mysql://${BIND_ADDRESS:localhost}:3306/web_order?useSSL=false&serverTimezone=UTC
    rabbitmq:
        host: ${BIND_ADDRESS:localhost}
        port: 5672
        username: guest
        password: guest
    redis:
        host: ${BIND_ADDRESS:localhost}
        port: 6379
env:
    dev-remote
